name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Cambia esto al nombre de tu rama principal si es diferente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          CI=false npm run-script build
        env:
          REACT_APP_YOUTUBE_API_KEY: ${{ secrets.REACT_APP_YOUTUBE_API_KEY }}

      - name: Configure Git remote with HTTPS
        run: git remote set-url origin https://github.com/Waldo-analista/programmingtube.git

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          branch: gh-pages
          folder: build

      - name: Clean up
        run: rm -rf build
